const mongoose = require('mongoose');
const { getModel } = require('../models/mongodb');

/**
 * MongoDB Adapter - Provides Firestore-compatible API for MongoDB/Mongoose
 * This allows controllers to use the same syntax for both Firestore and MongoDB
 */

/**
 * Build the "match this document id" filter. A Firestore doc id can be a Mongo
 * `_id`, our own `userId`, or a custom string id like `salesmanId`. Only include
 * the `_id` clause when the id actually looks like an ObjectId, otherwise Mongoose
 * throws a CastError on the `_id` branch (e.g. `.doc("SM-01")`).
 */
function buildIdQuery(docId) {
    const or = [{ userId: docId }, { salesmanId: docId }, { id: docId }];
    if (mongoose.isValidObjectId(docId)) {
        or.unshift({ _id: docId });
    }
    return { $or: or };
}

/**
 * Tenant-scope fields. Their values always come from the signed-in user's
 * scope (the collection's base query), never from a request body: a body
 * that sets `ownerId` must not be able to write into, or move a record to,
 * another store.
 */
const SCOPE_KEYS = ['_id', 'tenantId', 'ownerId', 'subuserId'];

function withoutScopeKeys(data) {
    const clean = { ...data };
    for (const key of SCOPE_KEYS) delete clean[key];
    return clean;
}

/**
 * Split a Firestore-style update payload into Mongo `$set` / `$inc`.
 * Values produced by `MongoFieldValue.increment(n)` look like `{ $inc: n }`.
 * Scope fields are dropped, so an update can never change a record's store.
 */
function toMongoUpdate(data) {
    const $set = {};
    const $inc = {};
    // Security: Protect immutable identification and creation timestamps from being tampered with
    const IMMUTABLE_KEYS = new Set(['_id', 'id', 'createdAt', 'ownerId', 'tenantId', 'createdBy']);

    for (const [key, value] of Object.entries(data)) {
        if (IMMUTABLE_KEYS.has(key)) continue;
        if (value && typeof value === 'object' && typeof value.$inc === 'number') {
            $inc[key] = value.$inc;
        } else {
            $set[key] = value;
        }
    }
    // Stamp updatedAt automatically if not provided
    if (!$set.updatedAt) {
        $set.updatedAt = new Date().toISOString();
    }

    const update = {};
    if (Object.keys($set).length) update.$set = $set;
    if (Object.keys($inc).length) update.$inc = $inc;
    return update;
}

class MongoDocumentReference {
    constructor(model, docId, query = {}) {
        this.model = model;
        this.docId = docId;
        this.query = query;
        // set when the id was auto-generated by `collection.doc()` with no argument
        this._generatedId = null;
    }

    // Firestore parity: `ref.id`
    get id() {
        return this.docId;
    }

    async get() {
        try {
            let doc;
            if (this.docId) {
                doc = await this.model.findOne({
                    ...buildIdQuery(this.docId),
                    ...this.query
                });
            } else {
                doc = await this.model.findOne(this.query);
            }

            return {
                exists: !!doc,
                id: doc?._id?.toString() || this.docId,
                data: () => {
                    if (!doc) return null;
                    const data = doc.toObject();
                    delete data._id;
                    delete data.__v;
                    return data;
                }
            };
        } catch (error) {
            console.error('MongoDocumentReference.get error:', error);
            throw error;
        }
    }

    async set(data) {
        try {
            // Fresh id from `collection.doc()` with no argument: this is a create.
            if (this._generatedId) {
                const newDoc = new this.model({
                    ...withoutScopeKeys(data),
                    ...this.query,
                    _id: this._generatedId
                });
                return await newDoc.save();
            }

            if (this.docId) {
                const result = await this.model.findOneAndUpdate(
                    {
                        ...buildIdQuery(this.docId),
                        ...this.query
                    },
                    toMongoUpdate(data),
                    { upsert: true, new: true, setDefaultsOnInsert: true }
                );
                return result;
            }

            const newDoc = new this.model({ ...withoutScopeKeys(data), ...this.query });
            return await newDoc.save();
        } catch (error) {
            console.error('MongoDocumentReference.set error:', error);
            throw error;
        }
    }

    async update(data) {
        try {
            const result = await this.model.findOneAndUpdate(
                {
                    ...buildIdQuery(this.docId),
                    ...this.query
                },
                toMongoUpdate(data),
                { new: true }
            );

            if (!result) {
                throw new Error('Document not found for update');
            }
            return result;
        } catch (error) {
            console.error('MongoDocumentReference.update error:', error);
            throw error;
        }
    }

    async delete() {
        try {
            await this.model.deleteOne({
                ...buildIdQuery(this.docId),
                ...this.query
            });
        } catch (error) {
            console.error('MongoDocumentReference.delete error:', error);
            throw error;
        }
    }

    collection(subCollection) {
        // For nested collections in MongoDB, we just return a new collection reference
        // Subcollections are handled via query filters (ownerId, subuserId, etc.)
        return new MongoCollectionReference(getModel(subCollection), this.query);
    }
}

class MongoCollectionReference {
    constructor(model, baseQuery = {}) {
        this.model = model;
        this.baseQuery = baseQuery;
        this.queryBuilder = null;
    }

    doc(docId) {
        if (docId) {
            return new MongoDocumentReference(this.model, docId, this.baseQuery);
        }
        // Firestore parity: `collection.doc()` with no arg mints a new id.
        const generated = new mongoose.Types.ObjectId();
        const ref = new MongoDocumentReference(this.model, generated.toString(), this.baseQuery);
        ref._generatedId = generated;
        return ref;
    }

    where(field, operator, value) {
        if (!this.queryBuilder) {
            this.queryBuilder = this.model.find(this.baseQuery);
        }

        switch (operator) {
            case '==':
                this.queryBuilder = this.queryBuilder.where(field).equals(value);
                break;
            case '!=':
                this.queryBuilder = this.queryBuilder.where(field).ne(value);
                break;
            case '>':
                this.queryBuilder = this.queryBuilder.where(field).gt(value);
                break;
            case '>=':
                this.queryBuilder = this.queryBuilder.where(field).gte(value);
                break;
            case '<':
                this.queryBuilder = this.queryBuilder.where(field).lt(value);
                break;
            case '<=':
                this.queryBuilder = this.queryBuilder.where(field).lte(value);
                break;
            case 'in':
                this.queryBuilder = this.queryBuilder.where(field).in(value);
                break;
            default:
                this.queryBuilder = this.queryBuilder.where(field).equals(value);
        }

        return this;
    }

    orderBy(field, direction = 'asc') {
        if (!this.queryBuilder) {
            this.queryBuilder = this.model.find(this.baseQuery);
        }
        const sortDir = direction === 'desc' ? -1 : 1;
        this.queryBuilder = this.queryBuilder.sort({ [field]: sortDir });
        return this;
    }

    limit(count) {
        if (!this.queryBuilder) {
            this.queryBuilder = this.model.find(this.baseQuery);
        }
        this.queryBuilder = this.queryBuilder.limit(count);
        return this;
    }

    async get() {
        try {
            const query = this.queryBuilder || this.model.find(this.baseQuery);
            const docs = await query.exec();

            const mapped = docs.map(doc => ({
                id: doc._id.toString(),
                exists: true,
                data: () => {
                    const data = doc.toObject();
                    delete data._id;
                    delete data.__v;
                    return data;
                }
            }));

            return {
                empty: mapped.length === 0,
                size: mapped.length,
                docs: mapped,
                // Firestore QuerySnapshot parity
                forEach: (cb) => mapped.forEach(cb)
            };
        } catch (error) {
            console.error('MongoCollectionReference.get error:', error);
            throw error;
        }
    }

    async add(data) {
        try {
            const newDoc = new this.model({ ...withoutScopeKeys(data), ...this.baseQuery });
            const saved = await newDoc.save();
            return {
                id: saved._id.toString()
            };
        } catch (error) {
            console.error('MongoCollectionReference.add error:', error);
            throw error;
        }
    }
}

/**
 * MongoDB Batch Operations
 */
class MongoBatch {
    constructor() {
        this.operations = [];
    }

    set(docRef, data) {
        this.operations.push({
            type: 'set',
            docRef,
            data
        });
    }

    update(docRef, data) {
        this.operations.push({
            type: 'update',
            docRef,
            data
        });
    }

    delete(docRef) {
        this.operations.push({
            type: 'delete',
            docRef
        });
    }

    async commit() {
        try {
            for (const op of this.operations) {
                switch (op.type) {
                    case 'set':
                        await op.docRef.set(op.data);
                        break;
                    case 'update':
                        await op.docRef.update(op.data);
                        break;
                    case 'delete':
                        await op.docRef.delete();
                        break;
                }
            }
            this.operations = [];
        } catch (error) {
            console.error('MongoBatch.commit error:', error);
            throw error;
        }
    }
}

/**
 * MongoDB FieldValue for special operations
 */
class MongoFieldValue {
    static increment(amount = 1) {
        return { $inc: amount };
    }

    static serverTimestamp() {
        return new Date().toISOString();
    }
}

module.exports = {
    MongoCollectionReference,
    MongoDocumentReference,
    MongoBatch,
    MongoFieldValue
};
